# Generated by Django 2.0.1 on 2018-03-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('nome', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
        ),
    ]
