# Generated by Django 2.0.1 on 2018-03-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('nome', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=80)),
                ('nome_file', models.CharField(max_length=80)),
                ('subfolder', models.CharField(blank=True, default='', max_length=80)),
                ('downloadfilename', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
        ),
        migrations.CreateModel(
            name='ReportAssociato',
            fields=[
                ('corso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('reports', models.TextField(blank=True, verbose_name='Lista dei report associati al corso')),
            ],
            options={
                'verbose_name': 'report associato',
                'verbose_name_plural': 'report associati',
            },
        ),
    ]
