# Generated by Django 2.0.1 on 2018-04-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportassociato',
            name='giorni_esame',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
