# Generated by Django 2.0.1 on 2018-03-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attesta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAssociato',
            fields=[
                ('corso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('reports', models.TextField(blank=True, verbose_name='Lista dei report associati al corso')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
        ),
    ]
