# Generated by Django 2.0.1 on 2018-03-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attesta', '0002_reportassociato'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='nome_file',
            field=models.CharField(default='pippo', max_length=80),
            preserve_default=False,
        ),
    ]
