# Generated by Django 2.0.1 on 2018-04-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attesta', '0002_reportassociato_giorni_esame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportassociato',
            name='giorni_esame',
            field=models.CharField(default='Non ancora assegnato', max_length=300),
        ),
    ]
