# Generated by Django 2.0.1 on 2018-03-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attesta', '0003_report_nome_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='subfolder',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
