# Generated by Django 2.0.1 on 2018-03-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attesta', '0004_report_subfolder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportassociato',
            options={'verbose_name': 'report associato', 'verbose_name_plural': 'report associati'},
        ),
    ]
