# Generated by Django 2.0.1 on 2018-02-10 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruoli', models.TextField(default=False, help_text="Lista dei ruoli che spettano all'utente", verbose_name="Ruoli assegnati all'utente")),
                ('permessi', models.TextField(blank=True, default=False, help_text="Lista dei permessi concessi all'utente", verbose_name='Permessi Concessi')),
                ('negati', models.TextField(blank=True, default=False, help_text="Lista dei permessi esplicitamente negati all'utente", verbose_name='Permessi Esplicitamente negati')),
                ('tmp_permessi', models.TextField(blank=True, default=False, help_text='Dizionario dei permessi temporaneamente concessi con timestamp di termine validità', verbose_name='Permessi temporaneamente concessi')),
                ('tmp_negati', models.TextField(blank=True, default=False, help_text='Dizionario dei permessi temporaneamente negati con timestamp di termine validità', verbose_name='Permessi temporaneamente negati')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
