# Generated by Django 2.1.3 on 2019-01-28 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruoli', models.TextField(default=False, help_text="Lista dei ruoli che spettano all'utente", verbose_name="Ruoli assegnati all'utente")),
                ('permessi', models.TextField(blank=True, default=False, help_text="Lista dei permessi concessi all'utente", verbose_name='Permessi Concessi')),
                ('negati', models.TextField(blank=True, default=False, help_text="Lista dei permessi esplicitamente negati all'utente", verbose_name='Permessi Esplicitamente negati')),
                ('tmp_permessi', models.TextField(blank=True, default=False, help_text='Dizionario dei permessi temporaneamente concessi con timestamp di termine validità', verbose_name='Permessi temporaneamente concessi')),
                ('tmp_negati', models.TextField(blank=True, default=False, help_text='Dizionario dei permessi temporaneamente negati con timestamp di termine validità', verbose_name='Permessi temporaneamente negati')),
                ('must_change_password', models.BooleanField(default=False, help_text="Se True l'utente deve cambiare la password al primo accesso")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profilo',
                'verbose_name_plural': 'profili',
            },
        ),
        migrations.CreateModel(
            name='Ruoli',
            fields=[
                ('ruolo', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='Nome del ruolo')),
                ('permessi', models.TextField(blank=True, default=False, help_text='Lista dei permessi concessi al ruolo', verbose_name='Permessi Concessi')),
                ('negati', models.TextField(blank=True, default=False, help_text='Lista dei permessi esplicitamente negati al ruolo', verbose_name='Permessi Esplicitamente negati')),
            ],
            options={
                'verbose_name': 'ruolo',
                'verbose_name_plural': 'ruoli',
            },
        ),
    ]
