# Generated by Django 2.0.1 on 2018-02-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruoli',
            fields=[
                ('ruolo', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='Nome del ruolo')),
                ('permessi', models.TextField(blank=True, default=False, help_text='Lista dei permessi concessi al ruolo', verbose_name='Permessi Concessi')),
                ('negati', models.TextField(blank=True, default=False, help_text='Lista dei permessi esplicitamente negati al ruolo', verbose_name='Permessi Esplicitamente negati')),
            ],
        ),
    ]
