# Generated by Django 2.0.1 on 2018-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ruoli'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text="Se True l'utente deve cambiare la password al primo accesso"),
        ),
    ]
