# Generated by Django 2.0.1 on 2018-03-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180218_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profilo', 'verbose_name_plural': 'profili'},
        ),
        migrations.AlterModelOptions(
            name='ruoli',
            options={'verbose_name': 'ruolo', 'verbose_name_plural': 'ruoli'},
        ),
    ]
