# Generated by Django 2.1.3 on 2019-01-28 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaboratori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoFormativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno_formativo', models.CharField(max_length=12, unique=True)),
                ('default', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Anno Formativo',
                'verbose_name_plural': 'Anni Formativi',
            },
        ),
        migrations.CreateModel(
            name='Autonomo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('valido_dal', models.DateField(verbose_name='Data di inizio validità')),
                ('valido_al', models.DateField(verbose_name='Data di fine validità')),
                ('documenti_consegnati', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
            ],
            options={
                'verbose_name': 'Collaborazione Autonoma',
                'verbose_name_plural': 'Collaborazioni Autonome',
            },
        ),
        migrations.CreateModel(
            name='CentroDiCosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('is_root', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Nome sintetico dell'iniziativa")),
                ('descrizione', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(5)], verbose_name="Breve descrizione dell'iniziativa")),
                ('cup', models.CharField(blank=True, max_length=30, verbose_name='CUP se presente')),
                ('cig', models.CharField(blank=True, max_length=30, verbose_name='CIG se presente')),
                ('iva_detraibile', models.BooleanField(default=True, verbose_name="L'IVA delle spese connesse all'iniziativa è scaricabile ?")),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
                ('valido_dal', models.DateField(verbose_name='Data di inizio validità')),
                ('valido_al', models.DateField(verbose_name='Data di fine validità')),
            ],
            options={
                'verbose_name': 'Centro di Costo',
                'verbose_name_plural': 'Centri di Costo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='IncaricoAttivitaVarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('numero', models.IntegerField()),
                ('data_incarico', models.DateField(auto_now=True)),
                ('data_inizio_incarico', models.DateField(auto_now=True)),
                ('data_termine_incarico', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncaricoDocenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('stato_incarico', models.IntegerField(choices=[(0, 'Bozza'), (1, 'Emesso'), (2, 'Firmato'), (3, 'In Corso'), (4, 'Chiuso'), (5, 'Liquidato')], default=0)),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('data_incarico', models.DateField(auto_now=True)),
                ('data_inizio_incarico', models.DateField(auto_now=True)),
                ('data_termine_incarico', models.DateField(auto_now=True)),
                ('tipologia_collaboratore', models.IntegerField(choices=[(0, 'Occasionale'), (1, 'CoCoCo/CoCoPro'), (2, 'Autonomo'), (3, 'Dipendente')], default=None)),
                ('materia', models.CharField(max_length=80)),
                ('ore_previste', models.FloatField()),
                ('ore_effettive', models.FloatField(default=0)),
                ('parametro_orario', models.FloatField()),
                ('aggiuntivo_corso', models.FloatField(default=0)),
                ('rimborso_spese_previsto', models.FloatField(default=0)),
                ('rimborso_spese_effettivo', models.FloatField(default=0)),
                ('importo_incarico_previsto', models.FloatField()),
                ('importo_incarico_effettivo', models.FloatField(default=0)),
                ('costo_incarico_previsto', models.FloatField()),
                ('costo_incarico_effettivo', models.FloatField(default=0)),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
                ('anno_formativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amm.AnnoFormativo')),
                ('collaboratore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collaboratori.Collaboratore')),
            ],
            options={
                'verbose_name': 'Incarico di Docenza',
                'verbose_name_plural': 'Incarichi di Docenza',
            },
        ),
        migrations.CreateModel(
            name='Occasionale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('valido_dal', models.DateField(verbose_name='Data di inizio validità')),
                ('valido_al', models.DateField(verbose_name='Data di fine validità')),
                ('documenti_consegnati', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
                ('collaboratore', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='collaboratori.Collaboratore')),
            ],
            options={
                'verbose_name': 'Collaborazione Occasionale',
                'verbose_name_plural': 'Collaborazioni Occasionali',
            },
        ),
        migrations.CreateModel(
            name='Parasubordinato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('valido_dal', models.DateField(verbose_name='Data di inizio validità')),
                ('valido_al', models.DateField(verbose_name='Data di fine validità')),
                ('documenti_consegnati', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
                ('collaboratore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collaboratori.Collaboratore')),
            ],
            options={
                'verbose_name': 'Collaborazione CoCoCo',
                'verbose_name_plural': 'Collaborazioni CoCoCo',
            },
        ),
        migrations.CreateModel(
            name='RilevamentoDocenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('ore_rilevate', models.IntegerField()),
                ('data_rilevazione', models.DateField(auto_now=True)),
                ('importo_da_liquidare', models.FloatField()),
                ('data_pagamento', models.DateField(auto_now=True)),
                ('incarico_docenza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amm.IncaricoDocenza')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
