# Generated by Django 2.0.1 on 2018-07-10 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iniziativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Nome sintetico dell'iniziativa")),
                ('descrizione', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(5)], verbose_name="Breve descrizione dell'iniziativa")),
                ('cup', models.CharField(blank=True, max_length=30, verbose_name='CUP se presente')),
                ('cig', models.CharField(blank=True, max_length=30, verbose_name='CIG se presente')),
                ('iva_detraibile', models.BooleanField(default=True, verbose_name="L'IVA delle spese connesse all'iniziativa è scaricabile ?")),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="L'iniziativa è tutt'ora in uso ?")),
                ('valido_dal', models.DateField(verbose_name='Data di inizio validità')),
                ('valido_al', models.DateField(verbose_name='Data di fine validità')),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'verbose_name': 'Iniziativa',
                'verbose_name_plural': 'Iniziative',
            },
        ),
    ]
