# Generated by Django 2.0.1 on 2018-07-10 15:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome sintetico del Progetto')),
                ('descrizione', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Breve descrizione del Progetto')),
                ('cup', models.CharField(blank=True, max_length=30, verbose_name='CUP se presente')),
                ('cig', models.CharField(blank=True, max_length=30, verbose_name='CIG se presente')),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('valido_dal', models.DateField(verbose_name='Data di inizio validità')),
                ('valido_al', models.DateField(verbose_name='Data di fine validità')),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SottoProgetto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome sintetico del Sotto-Progetto')),
                ('descrizione', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Breve descrizione del Sotto-Progetto')),
                ('cup', models.CharField(blank=True, max_length=30, verbose_name='CUP se presente')),
                ('cig', models.CharField(blank=True, max_length=30, verbose_name='CIG se presente')),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('valido_dal', models.DateField(verbose_name='Data di inizio validità')),
                ('valido_al', models.DateField(verbose_name='Data di fine validità')),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('progetto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amm.Progetto')),
            ],
            options={
                'verbose_name': 'Sotto-Progetto',
                'verbose_name_plural': 'Sotto Progetti',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='iniziativa',
            options={'ordering': ['nome'], 'verbose_name': 'Iniziativa', 'verbose_name_plural': 'Iniziative'},
        ),
        migrations.AlterField(
            model_name='iniziativa',
            name='in_uso',
            field=models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?"),
        ),
        migrations.AddField(
            model_name='progetto',
            name='iniziativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amm.Iniziativa'),
        ),
    ]
