# Generated by Django 2.1.3 on 2019-01-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corsi', '0001_initial'),
        ('anagrafe', '0001_initial'),
        ('collaboratori', '0001_initial'),
        ('amm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incaricodocenza',
            name='corso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corsi.Corso'),
        ),
        migrations.AddField(
            model_name='incaricoattivitavarie',
            name='collaboratore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collaboratori.Collaboratore'),
        ),
        migrations.AddField(
            model_name='centrodicosto',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iniziativa_parent', to='amm.CentroDiCosto'),
        ),
        migrations.AddField(
            model_name='centrodicosto',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iniziativa_root', to='amm.CentroDiCosto'),
        ),
        migrations.AddField(
            model_name='autonomo',
            name='collaboratore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collaboratori.Collaboratore'),
        ),
        migrations.AddField(
            model_name='autonomo',
            name='personainazienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anagrafe.PersonaInAzienda'),
        ),
    ]
