# Generated by Django 2.1 on 2018-09-01 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafe', '0007_auto_20180830_2305'),
        ('collaboratori', '0007_auto_20180830_2331'),
        ('amm', '0002_auto_20180710_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autonomo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('valido_dal', models.DateField(verbose_name='Data di inizio validità')),
                ('valido_al', models.DateField(verbose_name='Data di fine validità')),
                ('documenti_consegnati', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
                ('collaboratore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collaboratori.Collaboratore')),
                ('personainazienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anagrafe.PersonaInAzienda')),
            ],
            options={
                'verbose_name': 'Collaborazione Autonoma',
                'verbose_name_plural': 'Collaborazioni Autonome',
            },
        ),
        migrations.CreateModel(
            name='Occasionale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('valido_dal', models.DateField(verbose_name='Data di inizio validità')),
                ('valido_al', models.DateField(verbose_name='Data di fine validità')),
                ('documenti_consegnati', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
                ('collaboratore', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='collaboratori.Collaboratore')),
            ],
            options={
                'verbose_name': 'Collaborazione Occasionale',
                'verbose_name_plural': 'Collaborazioni Occasionali',
            },
        ),
        migrations.CreateModel(
            name='Parasubordinato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('valido_dal', models.DateField(verbose_name='Data di inizio validità')),
                ('valido_al', models.DateField(verbose_name='Data di fine validità')),
                ('documenti_consegnati', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
                ('collaboratore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collaboratori.Collaboratore')),
            ],
            options={
                'verbose_name': 'Collaborazione CoCoCo',
                'verbose_name_plural': 'Collaborazioni CoCoCo',
            },
        ),
    ]
