# Generated by Django 2.1 on 2018-09-06 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0004_iniziativa_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniziativa',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iniziativa',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iniziativa_root', to='amm.Iniziativa'),
        ),
        migrations.AlterField(
            model_name='iniziativa',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iniziativa_parent', to='amm.Iniziativa'),
        ),
    ]
