# Generated by Django 2.1 on 2018-09-06 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0005_auto_20180906_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniziativa',
            name='nome',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Nome sintetico dell'iniziativa"),
        ),
    ]
