# Generated by Django 2.1 on 2018-09-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corsi', '0003_auto_20180906_0840'),
        ('amm', '0006_auto_20180906_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progetto',
            name='iniziativa',
        ),
        migrations.RemoveField(
            model_name='sottoprogetto',
            name='progetto',
        ),
        migrations.DeleteModel(
            name='Progetto',
        ),
        migrations.DeleteModel(
            name='SottoProgetto',
        ),
    ]
