# Generated by Django 2.1 on 2018-09-06 08:42

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('corsi', '0003_auto_20180906_0840'),
        ('amm', '0007_auto_20180906_0840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Iniziativa',
            new_name='CentroDiCosto',
        ),
        migrations.AlterModelOptions(
            name='centrodicosto',
            options={'ordering': ['nome'], 'verbose_name': 'Centro di Costo', 'verbose_name_plural': 'Centri di Costo'},
        ),
    ]
