# Generated by Django 2.1 on 2018-09-10 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corsi', '0004_remove_corso_ordine_produzione'),
        ('collaboratori', '0007_auto_20180830_2331'),
        ('amm', '0008_auto_20180906_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncaricoAttivitaVarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('numero', models.IntegerField()),
                ('data_incarico', models.DateField(auto_now=True)),
                ('data_inizio_incarico', models.DateField(auto_now=True)),
                ('data_termine_incarico', models.DateField(auto_now=True)),
                ('collaboratore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collaboratori.Collaboratore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncaricoDocenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('numero', models.IntegerField()),
                ('data_incarico', models.DateField(auto_now=True)),
                ('data_inizio_incarico', models.DateField(auto_now=True)),
                ('data_termine_incarico', models.DateField(auto_now=True)),
                ('tipologia_collaboratore', models.IntegerField()),
                ('materia', models.CharField(max_length=80)),
                ('ore_previste', models.FloatField()),
                ('parametro_orario', models.FloatField()),
                ('aggiuntivo_corso', models.FloatField()),
                ('importo_incarico_previsto', models.FloatField()),
                ('importo_incarico_effettivo', models.FloatField()),
                ('costo_incarico_previsto', models.FloatField()),
                ('costo_incarico_effettivo', models.FloatField()),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
                ('cdc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amm.CentroDiCosto')),
                ('collaboratore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collaboratori.Collaboratore')),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corsi.Corso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RilevamentoDocenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('ore_rilevate', models.IntegerField()),
                ('data_rilevazione', models.DateField(auto_now=True)),
                ('importo_da_liquidare', models.FloatField()),
                ('data_pagamento', models.DateField(auto_now=True)),
                ('incarico_docenza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amm.IncaricoDocenza')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
