# Generated by Django 2.1 on 2018-09-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0010_auto_20180911_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='incaricodocenza',
            name='stato_incarico',
            field=models.IntegerField(choices=[(0, 'Bozza'), (1, 'Emesso'), (2, 'Firmato'), (3, 'In Corso'), (4, 'Chiuso'), (5, 'Liquidato')], default=0),
        ),
    ]
