# Generated by Django 2.1 on 2018-09-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0011_incaricodocenza_stato_incarico'),
    ]

    operations = [
        migrations.AddField(
            model_name='incaricodocenza',
            name='ore_effettive',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='incaricodocenza',
            name='costo_incarico_effettivo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='incaricodocenza',
            name='importo_incarico_effettivo',
            field=models.FloatField(default=0),
        ),
    ]
