# Generated by Django 2.1.2 on 2018-10-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0013_annoformativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incaricodocenza',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
