# Generated by Django 2.1.2 on 2018-11-04 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0014_auto_20181010_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='incaricodocenza',
            name='anno_formativo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='amm.AnnoFormativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incaricodocenza',
            name='rimborso_spese_effettivo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='incaricodocenza',
            name='rimborso_spese_previsto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='incaricodocenza',
            name='aggiuntivo_corso',
            field=models.FloatField(default=0),
        ),
    ]
