# Generated by Django 2.0.1 on 2018-07-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asc_id', models.BigIntegerField(default=None, null=True, unique=True)),
                ('asc_data_elemento', models.DateTimeField(blank=True, null=True)),
                ('asc_data_aggiornamento', models.DateTimeField(blank=True, null=True)),
                ('asc_ca_id', models.BigIntegerField(default=None, null=True, unique=True)),
                ('asc_ca_data_elemento', models.DateTimeField(blank=True, null=True)),
                ('asc_ca_data_aggiornamento', models.DateTimeField(blank=True, null=True)),
                ('r2k_id', models.BigIntegerField(default=None, null=True, unique=True)),
                ('r2k_data_elemento', models.DateTimeField(blank=True, null=True)),
                ('r2k_data_aggiornamento', models.DateTimeField(blank=True, null=True)),
                ('titolo', models.CharField(blank=True, max_length=20)),
                ('cognome', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('vip', models.BooleanField(default=False)),
                ('comune_nascita', models.CharField(blank=True, max_length=50)),
                ('provincia_nascita', models.CharField(blank=True, max_length=2)),
                ('stato_nascita', models.CharField(blank=True, max_length=40)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('cittadinanza', models.CharField(blank=True, max_length=40)),
                ('sesso', models.CharField(max_length=1)),
                ('indirizzo_domicilio', models.CharField(blank=True, max_length=50)),
                ('comune_domicilio', models.CharField(blank=True, max_length=50)),
                ('cap_domicilio', models.CharField(blank=True, max_length=5)),
                ('provincia_domicilio', models.CharField(blank=True, max_length=2)),
                ('regione_domicilio', models.CharField(blank=True, max_length=25)),
                ('stato_domicilio', models.CharField(blank=True, max_length=25)),
                ('indirizzo_residenza', models.CharField(blank=True, max_length=50)),
                ('comune_residenza', models.CharField(blank=True, max_length=50)),
                ('cap_residenza', models.CharField(blank=True, max_length=5)),
                ('provincia_residenza', models.CharField(blank=True, max_length=2)),
                ('regione_residenza', models.CharField(blank=True, max_length=25)),
                ('stato_residenza', models.CharField(blank=True, max_length=25)),
                ('cf', models.CharField(blank=True, max_length=16)),
                ('tel1', models.CharField(blank=True, max_length=30)),
                ('tel2', models.CharField(blank=True, max_length=30)),
                ('tel3', models.CharField(blank=True, max_length=30)),
                ('tel4', models.CharField(blank=True, max_length=30)),
                ('doc_tel1', models.CharField(blank=True, max_length=20)),
                ('doc_tel2', models.CharField(blank=True, max_length=20)),
                ('doc_tel3', models.CharField(blank=True, max_length=20)),
                ('doc_tel4', models.CharField(blank=True, max_length=20)),
                ('mail1', models.CharField(blank=True, max_length=50)),
                ('mail2', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True, verbose_name='Eventuali note')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Persone',
                'ordering': ['cognome'],
            },
        ),
    ]
