# Generated by Django 2.0.1 on 2018-08-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='doc_mail1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='doc_mail2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
