# Generated by Django 2.1 on 2018-08-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafe', '0002_auto_20180801_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTelefonoPersone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo Telefono',
                'verbose_name_plural': 'Tipi Telefono',
            },
        ),
    ]
