# Generated by Django 2.1 on 2018-08-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafe', '0003_tipotelefonopersone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMailPersone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_mail', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo Mail',
                'verbose_name_plural': 'Tipi Mail',
            },
        ),
    ]
