# Generated by Django 2.1 on 2018-08-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafe', '0004_tipomailpersone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asc_id', models.BigIntegerField(default=None, null=True, unique=True)),
                ('asc_data_elemento', models.DateTimeField(blank=True, null=True)),
                ('asc_data_aggiornamento', models.DateTimeField(blank=True, null=True)),
                ('r2k_id', models.BigIntegerField(default=None, null=True, unique=True)),
                ('r2k_data_elemento', models.DateTimeField(blank=True, null=True)),
                ('r2k_data_aggiornamento', models.DateTimeField(blank=True, null=True)),
                ('ragione_sociale', models.CharField(max_length=100)),
                ('descrizione', models.CharField(blank=True, max_length=200)),
                ('indirizzo', models.CharField(blank=True, max_length=50)),
                ('comune', models.CharField(blank=True, max_length=50)),
                ('cap', models.CharField(blank=True, max_length=5)),
                ('provincia', models.CharField(blank=True, max_length=2)),
                ('regione', models.CharField(blank=True, max_length=25)),
                ('stato', models.CharField(blank=True, max_length=25)),
                ('cf', models.CharField(max_length=16, verbose_name='Codice Fiscale')),
                ('piva', models.CharField(max_length=16, verbose_name='Partita Iva')),
                ('tel1', models.CharField(blank=True, max_length=30)),
                ('tel2', models.CharField(blank=True, max_length=30)),
                ('tel3', models.CharField(blank=True, max_length=30)),
                ('tel4', models.CharField(blank=True, max_length=30)),
                ('doc_tel1', models.CharField(blank=True, max_length=20)),
                ('doc_tel2', models.CharField(blank=True, max_length=20)),
                ('doc_tel3', models.CharField(blank=True, max_length=20)),
                ('doc_tel4', models.CharField(blank=True, max_length=20)),
                ('mail1', models.CharField(blank=True, max_length=50)),
                ('mail2', models.CharField(blank=True, max_length=50)),
                ('doc_mail1', models.CharField(blank=True, max_length=20)),
                ('doc_mail2', models.CharField(blank=True, max_length=20)),
                ('sito_web', models.CharField(blank=True, max_length=50)),
                ('hashragionesociale', models.CharField(max_length=100)),
                ('accetta_promozioni', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, verbose_name='Eventuali note')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='last_user',
            field=models.CharField(default='', max_length=80),
        ),
    ]
