# Generated by Django 2.1 on 2018-08-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafe', '0005_auto_20180827_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaInAzienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.CharField(blank=True, max_length=50)),
                ('tel1', models.CharField(blank=True, max_length=30)),
                ('tel2', models.CharField(blank=True, max_length=30)),
                ('tel3', models.CharField(blank=True, max_length=30)),
                ('tel4', models.CharField(blank=True, max_length=30)),
                ('doc_tel1', models.CharField(blank=True, max_length=20)),
                ('doc_tel2', models.CharField(blank=True, max_length=20)),
                ('doc_tel3', models.CharField(blank=True, max_length=20)),
                ('doc_tel4', models.CharField(blank=True, max_length=20)),
                ('mail1', models.CharField(blank=True, max_length=50)),
                ('mail2', models.CharField(blank=True, max_length=50)),
                ('doc_mail1', models.CharField(blank=True, max_length=20)),
                ('doc_mail2', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='Eventuali note')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(default='', max_length=80)),
            ],
            options={
                'verbose_name': 'Membro Azienda',
                'verbose_name_plural': 'Membri Aziende',
            },
        ),
        migrations.AlterModelOptions(
            name='azienda',
            options={'ordering': ['ragione_sociale'], 'verbose_name': 'Azienda', 'verbose_name_plural': 'Aziende'},
        ),
        migrations.AddField(
            model_name='personainazienda',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anagrafe.Azienda'),
        ),
        migrations.AddField(
            model_name='personainazienda',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anagrafe.Persona'),
        ),
    ]
