# Generated by Django 2.1 on 2018-08-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafe', '0006_auto_20180828_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azienda',
            name='last_user',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='persona',
            name='last_user',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='personainazienda',
            name='last_user',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
