# Generated by Django 2.1 on 2018-08-13 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratori', '0002_auto_20180813_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratore',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='anagrafe.Persona'),
        ),
    ]
