# Generated by Django 2.1 on 2018-08-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratori', '0003_auto_20180813_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratore',
            name='in_uso',
            field=models.BooleanField(db_index=True, default=True, help_text="Il collaboratore è tutt'ora attivo ?"),
        ),
    ]
