# Generated by Django 2.1 on 2018-08-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratori', '0004_auto_20180827_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('comune_nascita', models.CharField(max_length=50)),
                ('provincia_nascita', models.CharField(max_length=2)),
                ('stato_nascita', models.CharField(max_length=40)),
                ('data_nascita', models.DateField(null=True)),
                ('cittadinanza', models.CharField(max_length=40)),
                ('sesso', models.CharField(max_length=1)),
                ('indirizzo_domicilio', models.CharField(max_length=50)),
                ('comune_domicilio', models.CharField(max_length=50)),
                ('cap_domicilio', models.CharField(max_length=5)),
                ('provincia_domicilio', models.CharField(max_length=2)),
                ('stato_domicilio', models.CharField(max_length=25)),
                ('indirizzo_residenza', models.CharField(max_length=50)),
                ('comune_residenza', models.CharField(max_length=50)),
                ('cap_residenza', models.CharField(max_length=5)),
                ('provincia_residenza', models.CharField(max_length=2)),
                ('stato_residenza', models.CharField(max_length=25)),
                ('cf', models.CharField(max_length=16, unique=True)),
                ('tel1', models.CharField(max_length=30)),
                ('tel2', models.CharField(blank=True, max_length=30)),
                ('tel3', models.CharField(blank=True, max_length=30)),
                ('tel4', models.CharField(blank=True, max_length=30)),
                ('doc_tel1', models.CharField(max_length=20)),
                ('doc_tel2', models.CharField(blank=True, max_length=20)),
                ('doc_tel3', models.CharField(blank=True, max_length=20)),
                ('doc_tel4', models.CharField(blank=True, max_length=20)),
                ('mail1', models.CharField(blank=True, max_length=50)),
                ('mail2', models.CharField(blank=True, max_length=50)),
                ('doc_mail1', models.CharField(blank=True, max_length=20)),
                ('doc_mail2', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='Eventuali note')),
                ('data_inizio_collaborazione', models.DateField()),
                ('data_fine_collaborazione', models.DateField(blank=True, default=None, null=True)),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(default='', max_length=80)),
            ],
            options={
                'verbose_name': 'Dipendente',
                'verbose_name_plural': 'Dipendenti',
                'ordering': ['cognome'],
            },
        ),
    ]
