# Generated by Django 2.1 on 2018-08-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratori', '0005_dipendente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dipendente',
            name='regione_domicilio',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='regione_residenza',
        ),
    ]
