# Generated by Django 2.1 on 2018-08-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratori', '0005_dipendente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratore',
            name='in_uso',
            field=models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?"),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='last_user',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
