# Generated by Django 2.1 on 2018-08-30 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratori', '0006_auto_20180830_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratore',
            name='dipendente',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='collaboratori.Dipendente'),
        ),
        migrations.AlterField(
            model_name='collaboratore',
            name='persona',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='anagrafe.Persona'),
        ),
    ]
