# Generated by Django 2.1.3 on 2019-01-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafe', '0001_initial'),
        ('acquisti', '0001_initial'),
        ('amm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripartizionespesapercdc',
            name='cdc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amm.CentroDiCosto'),
        ),
        migrations.AddField(
            model_name='acquistoconordine',
            name='anno_formativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amm.AnnoFormativo'),
        ),
        migrations.AddField(
            model_name='acquistoconordine',
            name='fornitore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anagrafe.Fornitore'),
        ),
    ]
