# Generated by Django 2.1.3 on 2019-02-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisti', '0002_auto_20190128_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquistoconordine',
            name='numero_protocollo',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
