# Generated by Django 2.1.5 on 2019-02-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0002_auto_20190128_1300'),
        ('acquisti', '0004_acquistosuweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='RipartizioneAcquistoWebPerCDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('percentuale_di_competenza', models.DecimalField(decimal_places=2, max_digits=5)),
                ('costo_totale', models.DecimalField(decimal_places=2, max_digits=7)),
                ('acquisto_web', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acquisti.AcquistoSuWeb')),
                ('cdc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amm.CentroDiCosto')),
            ],
            options={
                'verbose_name': 'Ripartizione Acquisto Web su CDC',
                'verbose_name_plural': 'Ripartizione Acquisto Web su CDC',
            },
        ),
    ]
