# Generated by Django 2.1.3 on 2019-01-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('codice_edizione', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('denominazione', models.CharField(max_length=150)),
                ('durata', models.FloatField(default=8)),
                ('stato_corso', models.IntegerField(choices=[(0, 'Bozza'), (50, 'In Svolgimento'), (100, 'Terminato'), (150, 'Chiuso')], default=0)),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
                ('data_inizio', models.DateField()),
                ('data_inizio_annodoy', models.IntegerField(default=0)),
                ('data_fine', models.DateField()),
                ('data_fine_annodoy', models.IntegerField(default=0)),
                ('cdc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='amm.CentroDiCosto')),
            ],
            options={
                'verbose_name': 'Corso',
                'verbose_name_plural': 'Corsi',
            },
        ),
        migrations.CreateModel(
            name='OrdineProduzione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="Il record è tutt'ora in uso ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(blank=True, default='', max_length=80)),
                ('numero_ordine', models.CharField(max_length=10, unique=True)),
                ('data_inizio', models.DateField()),
                ('data_inizio_annodoy', models.IntegerField(default=0)),
                ('data_fine', models.DateField()),
                ('data_fine_annodoy', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, default='', verbose_name='Eventuali note')),
                ('cdc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='amm.CentroDiCosto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
