# Generated by Django 2.1 on 2018-09-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corsi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordineproduzione',
            name='iniziativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='amm.Iniziativa'),
        ),
        migrations.AlterField(
            model_name='ordineproduzione',
            name='progetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='amm.Progetto'),
        ),
        migrations.AlterField(
            model_name='ordineproduzione',
            name='sottoprogetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='amm.SottoProgetto'),
        ),
    ]
