# Generated by Django 2.1 on 2018-09-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corsi', '0002_auto_20180903_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordineproduzione',
            old_name='iniziativa',
            new_name='cdc',
        ),
        migrations.RemoveField(
            model_name='ordineproduzione',
            name='progetto',
        ),
        migrations.RemoveField(
            model_name='ordineproduzione',
            name='sottoprogetto',
        ),
    ]
