# Generated by Django 2.1 on 2018-09-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corsi', '0003_auto_20180906_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corso',
            name='ordine_produzione',
        ),
    ]
