# Generated by Django 2.1 on 2018-10-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corsi', '0007_auto_20180910_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='stato_corso',
            field=models.IntegerField(choices=[(0, 'Bozza'), (50, 'In Svolgimento'), (100, 'Terminato'), (150, 'Chiuso')], default=0),
        ),
    ]
